/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsDocumentIdRouteImport } from './routes/docs.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocumentIdRoute = DocsDocumentIdRouteImport.update({
  id: '/docs/$documentId',
  path: '/docs/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$documentId': typeof DocsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$documentId': typeof DocsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$documentId': typeof DocsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/$documentId'
  id: '__root__' | '/' | '/docs/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsDocumentIdRoute: typeof DocsDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$documentId': {
      id: '/docs/$documentId'
      path: '/docs/$documentId'
      fullPath: '/docs/$documentId'
      preLoaderRoute: typeof DocsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsDocumentIdRoute: DocsDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
