services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: duffle
    ports:
      - "3002:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    command:
      - -c
      - wal_level=logical
volumes:
  pgdata:
