/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnimationsRouteImport } from './routes/animations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsRoute = AnimationsRouteImport.update({
  id: '/animations',
  path: '/animations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/theme': typeof ThemeRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/theme': typeof ThemeRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/boards': typeof BoardsIndexRoute
  '/notes': typeof NotesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/animations': typeof AnimationsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/theme': typeof ThemeRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/animations'
    | '/login'
    | '/logout'
    | '/theme'
    | '/boards/$boardId'
    | '/notes/$noteId'
    | '/boards/'
    | '/notes/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/animations'
    | '/login'
    | '/logout'
    | '/theme'
    | '/boards/$boardId'
    | '/notes/$noteId'
    | '/boards'
    | '/notes'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/animations'
    | '/login'
    | '/logout'
    | '/theme'
    | '/boards/$boardId'
    | '/notes/$noteId'
    | '/boards/'
    | '/notes/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimationsRoute: typeof AnimationsRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ThemeRoute: typeof ThemeRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations': {
      id: '/animations'
      path: '/animations'
      fullPath: '/animations'
      preLoaderRoute: typeof AnimationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimationsRoute: AnimationsRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ThemeRoute: ThemeRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
