/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppLogoutRouteImport } from './routes/_app/logout'
import { Route as AppBoardsIndexRouteImport } from './routes/_app/boards.index'
import { Route as AppBoardsBoardIdRouteImport } from './routes/_app/boards.$boardId'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogoutRoute = AppLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBoardsIndexRoute = AppBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBoardsBoardIdRoute = AppBoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AppLoginRoute
  '/logout': typeof AppLogoutRoute
  '/boards/$boardId': typeof AppBoardsBoardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/boards/': typeof AppBoardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AppLoginRoute
  '/logout': typeof AppLogoutRoute
  '/boards/$boardId': typeof AppBoardsBoardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/boards': typeof AppBoardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/login': typeof AppLoginRoute
  '/_app/logout': typeof AppLogoutRoute
  '/_app/boards/$boardId': typeof AppBoardsBoardIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/boards/': typeof AppBoardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/logout' | '/boards/$boardId' | '/api/auth/$' | '/boards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/login' | '/logout' | '/boards/$boardId' | '/api/auth/$' | '/boards'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/login'
    | '/_app/logout'
    | '/_app/boards/$boardId'
    | '/api/auth/$'
    | '/_app/boards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/logout': {
      id: '/_app/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AppLogoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/boards/': {
      id: '/_app/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof AppBoardsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/boards/$boardId': {
      id: '/_app/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof AppBoardsBoardIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppLoginRoute: typeof AppLoginRoute
  AppLogoutRoute: typeof AppLogoutRoute
  AppBoardsBoardIdRoute: typeof AppBoardsBoardIdRoute
  AppBoardsIndexRoute: typeof AppBoardsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppLoginRoute: AppLoginRoute,
  AppLogoutRoute: AppLogoutRoute,
  AppBoardsBoardIdRoute: AppBoardsBoardIdRoute,
  AppBoardsIndexRoute: AppBoardsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
